!INTERFILE  :=
!imaging modality := PT
name of data file := 1104_span11.s
originating system := 1104
!version of keys := STIR3.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 9
matrix axis label [2] := view
!matrix size [2] := 168
matrix axis label [3] := axial coordinate
!matrix size [3] :={ 109,97,97,75,75,53,53,31,31 }
matrix axis label [1] := tangential coordinate
!matrix size [1] := 400
minimum ring difference per segment :={ -5,-16,6,-27,17,-38,28,-49,39 }
maximum ring difference per segment :={ 5,-6,16,-17,27,-28,38,-39,49 }
Scanner parameters:= 
Scanner type := Siemens mCT
Number of rings                          := 55
Number of detectors per ring             := 672
Inner ring diameter (cm)                 := 85.52
Average depth of interaction (cm)        := 0.7
Distance between rings (cm)              := 0.4054
Default bin size (cm)                    := 0.2005
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 400
Default number of arc-corrected bins     := 400
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 4
Number of crystals per block in axial direction             := 14
Number of crystals per block in transaxial direction        := 14
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 14
Number of crystals per singles unit in transaxial direction := 14
end scanner parameters:=
effective central bin size (cm) := 0.203174
number of time frames := 1
!END OF INTERFILE :=